In [1]:
import torch
import torchvision
import torch.nn as nn
import cv2
import random
import json
from typing import Literal
from pydantic import BaseModel
from pathlib import Path
import torch.optim as optim
import torch.nn.functional as F
import torchvision.transforms as transforms
from  torchvision import models 
from torch.utils.data import DataLoader, Dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
def train_val_test_split(
    csv_path: str | Path,
    train_matches: list[str],
    val_matches: list[str],
    test_matches: list[str],
    match_col: str = "match",
    img_name_col: str = "img_name",
) -> dict[str, list[str]]:
    """
    Dzieli dane na train/val/test na podstawie ręcznie podanych meczów.
    Przyjmuje ścieżkę do CSV z shot_labels (kolumny: img_name, label, match).
    Zwraca słownik: {"train": [nazwy zdjęć], "val": [...], "test": [...]}.
    """
    df = pd.read_csv(csv_path)
    
    if match_col not in df.columns:
        raise ValueError(f"Kolumna '{match_col}' nie istnieje w CSV. Dostępne: {list(df.columns)}")
    if img_name_col not in df.columns:
        raise ValueError(f"Kolumna '{img_name_col}' nie istnieje w CSV.")

    def img_names_for_matches(matches: list[str]) -> list[str]:
        mask = df[match_col].isin(matches)
        return df.loc[mask, img_name_col].astype(str).tolist()

    return {
        "train": img_names_for_matches(train_matches),
        "val": img_names_for_matches(val_matches),
        "test": img_names_for_matches(test_matches),
    }

In [3]:
df_labels = pd.read_csv('shot_labels.csv')

In [4]:
df_labels[['match']].value_counts()

match
m_pic       608
skip_m07    273
skip_m05    120
skip_m03    113
skip_m02    113
m02          99
skip_m09     60
m05          57
skip_m10     52
m04          50
m06          49
skip_m01     46
skip_m08     43
m01          40
skip_m04     37
m03          36
skip_m06     14
Name: count, dtype: int64

In [5]:
train_matches = ["m_pic", 'm01', 'm02', 'm03', "skip_m01", "skip_m02", 'skip_m03', "skip_m04", "skip_m05", "skip_m06", "skip_m07"] 
val_matches = ['m04', 'm05', 'm06', 'skip_m08', 'skip_m09', 'skip_m10'] 
test_matches = [ ]

split_spec = train_val_test_split(
    "shot_labels.csv",
    train_matches=train_matches,
    val_matches=val_matches,
    test_matches=test_matches,
)


with open("split_spec.json", "w", encoding="utf-8") as f:
    json.dump(split_spec, f, indent=4, ensure_ascii=False)

full_df = pd.read_csv("shot_labels.csv")
train_df = full_df[full_df["img_name"].isin(split_spec["train"])].reset_index(drop=True)
val_df = full_df[full_df["img_name"].isin(split_spec["val"])].reset_index(drop=True)
test_df = full_df[full_df["img_name"].isin(split_spec["test"])].reset_index(drop=True)

In [6]:
print(train_df['label'].value_counts(normalize=True))
print(val_df['label'].value_counts(normalize=True))
print(test_df['label'].value_counts(normalize=True))

label
1    0.522348
0    0.477652
Name: proportion, dtype: float64
label
1    0.501608
0    0.498392
Name: proportion, dtype: float64
Series([], Name: proportion, dtype: float64)

In [7]:
print(len(train_df))
print(len(val_df))

1499
311

In [8]:
def image_to_tensor(img: np.ndarray, resize: tuple[int, int] | None = None, with_batch_size: bool = True) -> torch.Tensor:
    if resize is not None:
        img = cv2.resize(img, resize)

    if img.ndim == 2:
        img = img[:, :, np.newaxis]

    img_tensor = torch.from_numpy(img).permute(2, 0, 1).float()
    return img_tensor.unsqueeze(0) if with_batch_size else img_tensor


def tensor_to_image(img_tensor: torch.Tensor) -> np.ndarray:
    if img_tensor.shape[0] > 1:
        raise ValueError("batch size must be equals to 1")
    
    img_arr = img_tensor.detach().numpy()
    return img_arr.squeeze()


def prepare_img_for_resnet(img: np.ndarray):
    img = cv2.resize(img, (224, 224)).astype(np.float32)
    img /= 255
    img_tensor = torch.tensor(img).permute(2, 0, 1).float()# .unsqueeze(0)
    return torchvision.transforms.functional.normalize(img_tensor, [0.485, 0.456, 0.406], [0.229, 0.224, 0.225])

In [9]:
class SnookerShotDataset(Dataset):
    def __init__(self, data_labels_path: str | Path, split_spec_path: str | Path, pics_root: str | Path = "../pics", mode: Literal['train', 'val', 'test'] = 'train'):
        self.pics_root = Path(pics_root)

        data = pd.read_csv(data_labels_path)
        split_spec = json.load(open(split_spec_path))
        self.data = data[data["img_name"].isin(split_spec[mode])].sample(frac=1).reset_index(drop=True)

    def __len__(self) -> int:
        return len(self.data)

    def _img_path(self, img_name: str) -> Path:
        subdir = "skip" if "skip_" in img_name else "."
        return self.pics_root / subdir / f"{img_name}.png"

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        row = self.data.iloc[idx]
        img_path = self._img_path(row["img_name"])

        img = cv2.imread(str(img_path)).astype(np.float32)
        img_tensor = prepare_img_for_resnet(img)
        label = torch.tensor(row["label"], dtype=torch.float32)

        return img_tensor, label

In [10]:
class History(BaseModel):
    epoch_losses: list[float] = []
    epoch_accuracy: list[float] = []
    step_losses: list[float] = []
    best_loss: float = np.inf
    best_accuracy: float = 0
    _running_loss: float
    _correct_pred: float

    def on_epoch_start(self) -> None:
        self._running_loss = .0
        self._correct_pred = .0

    def on_epoch_end(self, dataset: Dataset, focus: Literal['loss', 'accuracy']) -> bool:
        """
        Czy dana epoka polepszyla model wzgledem treningu na podstawie metryki przekazywanej w argumencie focus
        """
        current_loss = self._running_loss / len(dataset)
        current_accuracy = self._correct_pred / len(dataset)
        self.epoch_losses.append(current_loss)
        self.epoch_accuracy.append(current_accuracy)

        if is_better_loss := current_loss < self.best_loss:
            self.best_loss = current_loss
  
        if is_better_accuracy := current_accuracy > self.best_accuracy:
            self.best_accuracy = current_accuracy

        return  {'loss': is_better_loss, 'accuracy': is_better_accuracy}[focus]

        
    def on_step_end(self, loss: float, y_hat: torch.Tensor, y_gt: torch.Tensor) -> None:
        y_pred = (F.sigmoid(y_hat).reshape(-1) >= 0.5).long()
        self._correct_pred += (y_pred == y_gt).sum().item()
        self._running_loss += loss
        self.step_losses.append(loss)

        

    def get_latest(self, mode: Literal['train', 'val']) -> str:
        return f"{mode} loss= {self.epoch_losses[-1]:.4f} {mode} accuracy= {self.epoch_accuracy[-1]:.4f}"

In [11]:
train_dataset = SnookerShotDataset("shot_labels.csv", "split_spec.json", mode="train")
val_dataset = SnookerShotDataset("shot_labels.csv", "split_spec.json", mode="val")
# test_dataset = SnookerShotDataset("shot_labels.csv", "split_spec.json", mode="test")

In [12]:
train_dataloader = DataLoader(train_dataset, batch_size=1024, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=128)
# test_dataloader = DataLoader(test_dataset, batch_size=32)

In [13]:
weights = models.ResNet18_Weights.DEFAULT
model = models.resnet18(weights=weights)

In [14]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Linear(in_features=512, out_features=1000, bias=True)
)

In [15]:
model.fc.in_features # liczba cech do glowy

model.fc = nn.Sequential(
    nn.Linear(model.fc.in_features, 256),
    nn.ReLU(),
    nn.Dropout(0.4),
    nn.Linear(256, 64),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(64, 1),
)

In [16]:
# model

In [17]:
for name, param in model.named_parameters():
    if not name.startswith(('fc', 
                            'layer4.1.conv2.weight', 'layer4.1.bn2.weight', 'layer4.1.bn2.bias', 
                             'layer4.1.conv1.weight', 'layer4.1.bn1.weight', 'layer4.1.bn1.bias', 
                            
                            'layer4.0.conv1.weight', 'layer4.0.bn1.weight', 'layer4.0.bn1.bias',
                            'layer4.0.conv2.weight', 'layer4.0.bn2.weight', 'layer4.0.bn2.bias'
                            
                            )): 
        param.requires_grad = False

In [ ]:
torch.manual_seed(123)
np.random.seed(123)
random.seed(123)


criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
epochs_num = 10
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", patience=4)
focus = "loss"
model = model.to(device)

train_hist = History()
val_hist = History()
learning_rates = []

for ep in range(epochs_num):
    model.train()

    train_hist.on_epoch_start()

    for batch_x, batch_y in train_dataloader:
        optimizer.zero_grad()
        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)  
        y_hat = model(batch_x)


        loss = criterion(y_hat, batch_y.reshape(-1, 1))
        loss.backward()
        optimizer.step()
        train_hist.on_step_end(loss.item(), y_hat, batch_y)

    train_hist.on_epoch_end(train_dataset, focus)
    model.eval()
    val_hist.on_epoch_start()
    with torch.no_grad():

        for batch_x, batch_y in val_dataloader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)
            y_hat = model(batch_x)

            loss = criterion(y_hat, batch_y.reshape(-1, 1))
            val_hist.on_step_end(loss.item(), y_hat, batch_y)


    save_best_model = val_hist.on_epoch_end(val_dataset, focus)
    scheduler.step(val_hist.epoch_losses[-1])
    learning_rates.append(optimizer.param_groups[0]['lr'])
    print(f"Epoka {ep+1}/{epochs_num}: {train_hist.get_latest(mode='train')}, {val_hist.get_latest('val')}")

    checkpoint_data = {"model": model.state_dict(), "optimizer": optimizer.state_dict(), "epoch": ep + 1}
    torch.save(checkpoint_data, '../models/shot-classifier-last.pt')
    if save_best_model:
        torch.save(checkpoint_data, '../models/shot-classifier-best.pt')

Epoka 1/10: train loss= 0.0009 train accuracy= 0.5103, val loss= 0.0061 val accuracy= 0.5949
Epoka 2/10: train loss= 0.0007 train accuracy= 0.8419, val loss= 0.0051 val accuracy= 0.9518
Epoka 3/10: train loss= 0.0006 train accuracy= 0.9506, val loss= 0.0042 val accuracy= 0.9678
Epoka 4/10: train loss= 0.0005 train accuracy= 0.9833, val loss= 0.0034 val accuracy= 0.9711
Epoka 5/10: train loss= 0.0004 train accuracy= 0.9913, val loss= 0.0028 val accuracy= 0.9775
Epoka 6/10: train loss= 0.0003 train accuracy= 0.9933, val loss= 0.0024 val accuracy= 0.9775
Epoka 7/10: train loss= 0.0003 train accuracy= 0.9987, val loss= 0.0021 val accuracy= 0.9775
Epoka 8/10: train loss= 0.0002 train accuracy= 0.9987, val loss= 0.0018 val accuracy= 0.9807
Epoka 9/10: train loss= 0.0002 train accuracy= 0.9993, val loss= 0.0016 val accuracy= 0.9807
Epoka 10/10: train loss= 0.0002 train accuracy= 0.9993, val loss= 0.0015 val accuracy= 0.9807

In [40]:
model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")


img = cv2.imread('/home/polymorvic/development/deep-peep-snooker/skip_test.png').astype(np.float32)  # skip_test
img = prepare_img_for_resnet(img)
img = img.unsqueeze(0)
img = img.to(device)

with torch.no_grad():
    y_hat = model(img)
    probs = F.sigmoid(y_hat)

In [41]:
probs

tensor([[0.0258]], device='cuda:0')

device(type='cuda')

In [ ]:
# load_model = models.resnet18(weights=None)


# load_model.fc = nn.Sequential(
#     nn.Linear(load_model.fc.in_features, 256),
#     nn.ReLU(),
#     nn.Dropout(0.4),
#     nn.Linear(256, 64),
#     nn.ReLU(),
#     nn.Dropout(0.3),
#     nn.Linear(64, 1),
# )


# load_model.state_dict(torch.load('/home/polymorvic/development/deep-peep-snooker/models/v5/shot-classifier-best.pt'))

/tmp/ipykernel_10898/4220285649.py:15: FutureWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  load_model.state_dict(torch.load('/home/polymorvic/development/deep-peep-snooker/models/v5/shot-classifier-best.pt'))

{'model': OrderedDict([('conv1.weight',
               tensor([[[[-1.0419e-02, -6.1356e-03, -1.8098e-03,  ...,  5.6615e-02,
                           1.7083e-02, -1.2694e-02],
                         [ 1.1083e-02,  9.5276e-03, -1.0993e-01,  ..., -2.7124e-01,
                          -1.2907e-01,  3.7424e-03],
                         [-6.9434e-03,  5.9089e-02,  2.9548e-01,  ...,  5.1972e-01,
                           2.5632e-01,  6.3573e-02],
                         ...,
                         [-2.7535e-02,  1.6045e-02,  7.2595e-02,  ..., -3.3285e-01,
                          -4.2058e-01, -2.5781e-01],
                         [ 3.0613e-02,  4.0960e-02,  6.2850e-02,  ...,  4.1384e-01,
                           3.9359e-01,  1.6606e-01],
                         [-1.3736e-02, -3.6746e-03, -2.4084e-02,  ..., -1.5070e-01,
                          -8.2230e-02, -5.7828e-03]],

                        [[-1.1397e-02, -2.6619e-02, -3.4641e-02,  ...,  3.2521e-02,
                           6.6221e-04, -2.5743e-02],
                         [ 4.5687e-02,  3.3603e-02, -1.0453e-01,  ..., -3.1253e-01,
                          -1.6051e-01, -1.2826e-03],
                         [-8.3730e-04,  9.8420e-02,  4.0210e-01,  ...,  7.0789e-01,
                           3.6887e-01,  1.2455e-01],
                         ...,
                         [-5.5926e-02, -5.2239e-03,  2.7081e-02,  ..., -4.6178e-01,
                          -5.7080e-01, -3.6552e-01],
                         [ 3.2860e-02,  5.5574e-02,  9.9670e-02,  ...,  5.4636e-01,
                           4.8276e-01,  1.9867e-01],
                         [ 5.3051e-03,  6.6938e-03, -1.7254e-02,  ..., -1.4822e-01,
                          -7.7248e-02,  7.2183e-04]],

                        [[-2.0315e-03, -9.1617e-03,  2.1209e-02,  ...,  8.9177e-02,
                           3.3655e-02, -2.0102e-02],
                         [ 1.5398e-02, -1.8648e-02, -1.2591e-01,  ..., -2.5342e-01,
                          -1.2980e-01, -2.7975e-02],
                         [ 9.8454e-03,  4.9047e-02,  2.1699e-01,  ...,  3.4872e-01,
                           1.0433e-01,  1.8413e-02],
                         ...,
                         [-2.8356e-02,  1.8404e-02,  9.8647e-02,  ..., -1.1740e-01,
                          -2.5760e-01, -1.5451e-01],
                         [ 2.0766e-02, -2.6286e-03, -3.7825e-02,  ...,  2.4141e-01,
                           2.4345e-01,  1.1796e-01],
                         [ 7.4684e-04,  7.7677e-04, -1.0050e-02,  ..., -1.4865e-01,
                          -1.1754e-01, -3.8350e-02]]],


                       [[[-4.4154e-03, -4.0645e-03,  3.1589e-03,  ..., -3.7026e-02,
                          -2.5158e-02, -4.7945e-02],
                         [ 5.1310e-02,  5.3402e-02,  8.0436e-02,  ...,  1.4480e-01,
                           1.4287e-01,  1.2312e-01],
                         [-7.3337e-03,  2.1755e-03,  3.7580e-02,  ...,  6.1517e-02,
                           8.0324e-02,  1.1715e-01],
                         ...,
                         [-2.6754e-02, -1.2297e-01, -1.3653e-01,  ..., -1.4068e-01,
                          -1.1155e-01, -4.9556e-02],
                         [ 2.3524e-02, -1.7288e-02, -1.1122e-02,  ..., -1.8826e-02,
                          -2.3320e-02, -2.9474e-02],
                         [ 2.8689e-02,  2.1659e-02,  4.7888e-02,  ...,  2.5498e-02,
                           3.5346e-02,  1.1280e-02]],

                        [[ 4.6919e-04,  1.2153e-02,  4.2035e-02,  ...,  4.6403e-02,
                           4.0423e-02, -1.4439e-02],
                         [ 4.3463e-02,  6.8779e-02,  1.3268e-01,  ...,  2.8606e-01,
                           2.6905e-01,  2.0935e-01],
                         [-5.7621e-02, -2.2642e-02,  3.0547e-02,  ...,  1.3763e-01,
                           1.6538e-01,  1.7946e-01],
                         ...,
                         [-1.0816e-01, -2.5227e-01, -2.9742e-01,  ..., -2.8503e-01,
                          -2.1493e-01, -1.0320e-01],
                         [ 4.0709e-02, -3.2771e-02, -6.3450e-02,  ..., -9.2360e-02,
                          -6.9876e-02, -4.9841e-02],
                         [ 8.2942e-02,  8.7580e-02,  1.0111e-01,  ...,  5.2714e-02,
                           6.0968e-02,  4.1198e-02]],

                        [[-1.6391e-02, -1.3870e-02,  5.2810e-03,  ...,  4.3698e-02,
                           2.2707e-02, -4.5983e-02],
                         [ 3.3202e-02,  4.2014e-02,  9.3500e-02,  ...,  2.6162e-01,
                           2.2970e-01,  1.6694e-01],
                         [-4.5987e-02, -1.6365e-02,  2.6811e-02,  ...,  1.4951e-01,
                           1.3216e-01,  1.3579e-01],
                         ...,
                         [-7.2129e-02, -1.8902e-01, -2.3389e-01,  ..., -1.9038e-01,
                          -1.5609e-01, -7.5974e-02],
                         [ 5.1161e-02, -2.5815e-02, -6.9357e-02,  ..., -5.8999e-02,
                          -6.1550e-02, -4.4555e-02],
                         [ 1.1174e-01,  7.8979e-02,  6.5849e-02,  ...,  3.1617e-02,
                           2.5221e-02,  7.4257e-03]]],


                       [[[-7.0826e-08, -6.4306e-08, -7.3806e-08,  ..., -9.8000e-08,
                          -1.0905e-07, -8.3421e-08],
                         [-6.1125e-09,  2.0613e-09, -8.0922e-09,  ..., -4.9840e-08,
                          -4.3836e-08, -3.0538e-09],
                         [ 7.1953e-08,  7.5616e-08,  5.9282e-08,  ..., -9.7509e-09,
                          -1.0951e-09,  4.2442e-08],
                         ...,
                         [ 9.5889e-08,  1.0039e-07,  7.9817e-08,  ..., -1.7491e-08,
                          -4.7666e-08, -1.3265e-08],
                         [ 1.2904e-07,  1.4762e-07,  1.7477e-07,  ...,  1.3233e-07,
                           1.0628e-07,  9.3316e-08],
                         [ 1.2558e-07,  1.3644e-07,  1.8431e-07,  ...,  2.1399e-07,
                           1.7710e-07,  1.7166e-07]],

                        [[-1.2690e-07, -9.6139e-08, -1.0372e-07,  ..., -1.1808e-07,
                          -1.3309e-07, -1.0820e-07],
                         [-5.7412e-08, -2.5055e-08, -3.0115e-08,  ..., -7.2922e-08,
                          -6.7022e-08, -2.2574e-08],
                         [ 2.1813e-08,  4.8608e-08,  3.1222e-08,  ..., -1.8694e-08,
                          -7.9591e-09,  3.9750e-08],
                         ...,
                         [ 5.6013e-08,  7.5526e-08,  4.4496e-08,  ..., -4.4128e-08,
                          -5.9930e-08, -1.8247e-08],
                         [ 7.7614e-08,  9.8348e-08,  1.0455e-07,  ...,  6.3272e-08,
                           4.1781e-08,  4.5901e-08],
                         [ 5.9834e-08,  7.1006e-08,  9.0437e-08,  ...,  1.1654e-07,
                           8.7550e-08,  9.8837e-08]],

                        [[-4.3810e-08,  1.3270e-08,  7.8275e-09,  ..., -5.8804e-09,
                          -2.6217e-08, -1.5649e-08],
                         [ 4.1700e-08,  1.0778e-07,  1.0946e-07,  ...,  7.6403e-08,
                           7.1450e-08,  9.7615e-08],
                         [ 1.0436e-07,  1.6586e-07,  1.5933e-07,  ...,  1.3517e-07,
                           1.3487e-07,  1.6449e-07],
                         ...,
                         [ 9.8763e-08,  1.5072e-07,  1.2547e-07,  ...,  6.8316e-08,
                           6.8382e-08,  1.1367e-07],
                         [ 9.1435e-08,  1.3576e-07,  1.3793e-07,  ...,  1.1678e-07,
                           1.1723e-07,  1.4394e-07],
                         [ 6.2183e-08,  8.8184e-08,  1.0456e-07,  ...,  1.3941e-07,
                           1.3333e-07,  1.5844e-07]]],


                       ...,


                       [[[-6.1896e-02, -3.0206e-02,  1.9225e-02,  ...,  4.3665e-02,
                          -2.2114e-02, -4.2214e-02],
                         [-3.8061e-02,  6.0774e-03,  4.5797e-02,  ...,  9.6029e-02,
                           5.9254e-02,  2.9958e-02],
                         [-2.9672e-02,  2.7766e-03,  2.0457e-02,  ...,  5.9828e-02,
                           4.1422e-02,  2.3134e-02],
                         ...,
                         [ 1.1916e-02,  4.5701e-02,  4.4892e-02,  ...,  4.7419e-02,
                           2.2274e-02, -5.4993e-03],
                         [-3.2468e-02, -1.2210e-02,  2.2023e-02,  ...,  5.8061e-02,
                          -7.5033e-03, -5.9736e-02],
                         [-4.3314e-02, -2.8162e-02, -5.9126e-03,  ...,  8.8460e-02,
                           8.4406e-03, -5.0019e-02]],

                        [[-6.1292e-02, -1.4004e-02,  1.7229e-02,  ...,  1.8349e-02,
                          -3.2708e-02, -4.1060e-02],
                         [-3.1506e-02,  2.4460e-02,  4.5516e-02,  ...,  6.6806e-02,
                           4.6687e-02,  3.3248e-02],
                         [-3.2216e-02,  2.0718e-02,  2.3343e-02,  ...,  3.5265e-02,
                           3.6478e-02,  3.1291e-02],
                         ...,
                         [ 1.7739e-02,  6.1040e-02,  4.8247e-02,  ...,  3.7785e-02,
                           2.8894e-02,  1.3984e-02],
                         [-1.0890e-02,  2.2079e-02,  4.2737e-02,  ...,  6.0247e-02,
                           1.6197e-02, -1.2493e-02],
                         [-2.2284e-02,  1.3220e-02,  3.0897e-02,  ...,  1.0403e-01,
                           4.0119e-02, -5.3310e-03]],

                        [[-8.5322e-02, -4.2603e-02,  6.8145e-03,  ...,  3.0751e-02,
                          -3.4818e-02, -4.9945e-02],
                         [-2.9215e-02,  1.8165e-02,  5.1092e-02,  ...,  9.0200e-02,
                           5.3438e-02,  4.0169e-02],
                         [-3.9932e-02, -1.1100e-03,  9.6176e-03,  ...,  2.4114e-02,
                           2.6298e-02,  2.5489e-02],
                         ...,
                         [-3.1890e-03,  3.0454e-02,  1.6316e-02,  ...,  5.5054e-03,
                          -6.2689e-03, -8.4638e-03],
                         [-2.2995e-02, -2.8211e-03,  2.3203e-02,  ...,  3.5888e-02,
                          -1.4296e-02, -3.2419e-02],
                         [-9.8894e-03,  7.0542e-03,  1.0659e-02,  ...,  7.0495e-02,
                           1.2996e-02, -8.3417e-03]]],


                       [[[-7.8699e-03,  1.9911e-02,  3.4208e-02,  ...,  2.8694e-02,
                           1.2820e-02,  1.8142e-02],
                         [ 8.7942e-03, -3.2875e-02, -3.5713e-02,  ...,  7.2533e-02,
                           4.5889e-02,  5.2383e-02],
                         [-3.6122e-02, -1.1878e-01, -1.3767e-01,  ...,  3.3811e-02,
                           3.7806e-02,  2.6944e-02],
                         ...,
                         [ 1.7322e-02,  3.9589e-03, -8.2269e-03,  ...,  2.7543e-03,
                           1.8313e-02,  1.6057e-02],
                         [-9.5007e-04,  1.6428e-02,  1.7156e-02,  ...,  3.3672e-03,
                           2.2857e-02,  6.5783e-04],
                         [ 6.1727e-03,  2.7145e-02,  1.4340e-02,  ...,  7.5867e-03,
                           1.8770e-02,  1.5624e-02]],

                        [[-1.3423e-02, -5.0696e-04,  8.0959e-03,  ..., -6.0963e-03,
                           9.2341e-03,  1.5751e-02],
                         [-1.8343e-02, -6.7982e-02, -7.0685e-02,  ...,  2.9855e-02,
                           2.6264e-02,  2.3773e-02],
                         [-5.4359e-02, -1.4663e-01, -1.6211e-01,  ...,  1.1781e-02,
                           3.2477e-02,  1.1980e-02],
                         ...,
                         [ 8.3686e-04, -1.7564e-02, -1.9535e-02,  ..., -4.1382e-03,
                           2.4658e-02,  1.2893e-02],
                         [-6.3183e-04,  1.1788e-02,  2.4810e-02,  ...,  6.1105e-03,
                           3.9210e-02,  9.6696e-03],
                         [-7.1831e-03,  6.6918e-03,  5.2723e-03,  ..., -7.6077e-03,
                           2.7253e-02,  1.7735e-02]],

                        [[-2.3753e-04, -4.9343e-03,  2.2991e-03,  ..., -4.7958e-02,
                          -2.6154e-02, -2.3525e-02],
                         [-3.3053e-04, -5.1502e-02, -5.9977e-02,  ..., -1.7369e-02,
                          -2.3337e-02, -3.7312e-02],
                         [-2.2674e-02, -9.9412e-02, -1.1176e-01,  ..., -1.1725e-02,
                          -8.3744e-03, -4.0615e-02],
                         ...,
                         [ 1.1437e-02, -8.0313e-03, -1.4955e-03,  ..., -3.4133e-02,
                          -8.7267e-03, -2.3526e-02],
                         [ 2.9522e-03,  6.7770e-04,  1.9933e-02,  ..., -2.2002e-02,
                           1.4814e-02, -1.4487e-02],
                         [-1.9085e-02, -2.9430e-02, -2.3284e-02,  ..., -4.8587e-02,
                          -1.3049e-02, -2.4368e-02]]],


                       [[[-3.6296e-02,  7.1996e-03,  1.9100e-02,  ...,  1.9602e-02,
                           1.4870e-02, -1.7298e-02],
                         [-1.1061e-02,  8.5665e-02,  1.2667e-01,  ...,  1.3744e-02,
                          -5.5036e-05, -3.0162e-02],
                         [ 1.1322e-01,  1.8634e-01,  5.0658e-02,  ..., -1.7333e-01,
                          -7.2041e-02, -6.2474e-02],
                         ...,
                         [-5.3062e-02, -2.5781e-01, -2.6747e-01,  ...,  2.6781e-01,
                           1.4344e-01,  5.5145e-02],
                         [-2.1009e-02, -2.9969e-02,  1.0245e-01,  ...,  2.0843e-01,
                          -4.1518e-03, -3.8118e-02],
                         [-2.2155e-02,  1.2380e-02,  8.4302e-02,  ..., -4.4992e-02,
                          -1.4687e-01, -9.0890e-02]],

                        [[-5.3969e-03,  3.2799e-02,  1.5486e-02,  ..., -7.7451e-03,
                           3.0229e-03,  1.1216e-03],
                         [ 6.1723e-02,  1.4899e-01,  1.4645e-01,  ..., -2.8897e-02,
                          -2.0227e-02, -9.1878e-03],
                         [ 1.6146e-01,  2.0886e-01, -2.5589e-02,  ..., -2.7278e-01,
                          -1.0735e-01, -6.2971e-02],
                         ...,
                         [-1.3723e-01, -4.0863e-01, -3.8551e-01,  ...,  4.0846e-01,
                           2.6202e-01,  1.3491e-01],
                         [-5.9388e-02, -6.1187e-02,  1.4197e-01,  ...,  3.5780e-01,
                           9.0893e-02, -1.7392e-03],
                         [ 7.8613e-03,  5.8403e-02,  1.5339e-01,  ...,  4.7045e-02,
                          -1.0095e-01, -9.7920e-02]],

                        [[-5.6799e-03,  1.3425e-02, -2.6461e-02,  ...,  4.4881e-03,
                           2.0666e-03,  1.3902e-02],
                         [ 6.5943e-03,  4.5181e-02,  6.0260e-02,  ...,  1.4368e-02,
                          -5.0725e-03,  4.0505e-03],
                         [ 5.5257e-02,  1.2397e-01,  4.3193e-02,  ..., -1.4486e-01,
                          -7.4489e-02, -5.7533e-02],
                         ...,
                         [-3.1513e-02, -1.6334e-01, -1.5795e-01,  ...,  2.2904e-01,
                           1.2017e-01,  7.1998e-02],
                         [-1.0456e-02, -1.1248e-03,  8.4582e-02,  ...,  1.5748e-01,
                           2.2142e-02, -1.0083e-02],
                         [-4.8639e-03, -5.0065e-03,  3.6341e-02,  ..., -2.4361e-02,
                          -7.1195e-02, -6.6788e-02]]]], device='cuda:0')),
              ('bn1.weight',
               tensor([ 2.3487e-01,  2.6626e-01, -5.1096e-08,  5.1870e-01,  3.4404e-09,
                        2.2239e-01,  4.2289e-01,  1.3153e-07,  2.5093e-01,  1.5152e-06,
                        3.1687e-01,  2.5049e-01,  3.7893e-01,  1.0862e-05,  2.7526e-01,
                        2.3674e-01,  2.4202e-01,  3.9531e-01,  4.6935e-01,  2.9090e-01,
                        2.7268e-01,  2.7803e-01,  2.9069e-01,  2.0693e-01,  2.5899e-01,
                        2.7871e-01,  2.9115e-01,  3.1601e-01,  3.8889e-01,  3.0411e-01,
                        2.6776e-01,  2.1093e-01,  2.8708e-01,  3.3243e-01,  4.2673e-01,
                        3.7326e-01,  7.4804e-08,  1.9068e-01,  1.4740e-08,  2.2303e-01,
                        1.7908e-01,  2.4860e-01,  2.7400e-01,  2.5923e-01,  2.9420e-01,
                        2.9924e-01,  2.2369e-01,  2.6280e-01,  2.2001e-08,  2.6610e-01,
                        2.2089e-01,  2.8429e-01,  3.3072e-01,  2.2681e-01,  3.6538e-01,
                        2.1230e-01,  2.3965e-01,  2.4950e-01,  5.2583e-01,  2.4825e-01,
                        2.9565e-01,  2.5878e-01,  4.8326e-01,  2.6670e-01], device='cuda:0')),
              ('bn1.bias',
               tensor([ 2.3072e-01,  2.5382e-01, -1.0543e-06, -6.6439e-01, -1.6571e-08,
                        1.6152e-01,  4.5450e-01, -4.3020e-07,  3.0051e-01, -8.0052e-06,
                        3.4942e-01,  3.1148e-01, -2.4953e-01, -3.4749e-05,  1.0773e-01,
                        2.1897e-01,  3.8141e-01, -5.2988e-01, -6.2864e-01,  5.7140e-01,
                        2.9985e-01,  5.8430e-01,  4.8202e-01,  3.2853e-01,  1.9672e-01,
                        1.9496e-01,  1.5215e-01,  8.5522e-02,  5.1314e-01,  1.5237e-02,
                        1.6644e-01,  3.3239e-01,  2.4921e-01,  4.4337e-01, -2.8017e-01,
                       -2.0385e-02, -2.4507e-07,  3.2134e-01, -4.9152e-08,  2.3777e-01,
                        2.3291e-01,  3.1527e-01,  4.2776e-01,  2.9313e-01,  2.6379e-01,
                        6.7598e-01,  4.2910e-01,  3.4566e-01, -8.6909e-08,  2.4729e-01,
                        3.0316e-01,  6.1577e-01,  3.9835e-01,  3.3207e-01, -4.1219e-01,
                        3.7807e-01,  1.7895e-01,  2.5748e-01, -4.4908e-01,  2.1306e-01,
                        5.6934e-01,  5.7274e-01, -4.0238e-01,  2.3406e-01], device='cuda:0')),
              ('bn1.running_mean',
               tensor([-1.1161e-01,  5.6735e-01, -6.1295e-06,  1.5513e+00, -3.1248e-07,
                       -2.7743e-02, -1.2436e+00,  2.3513e-06,  1.2130e-01, -2.1238e-05,
                       -7.9182e-01, -6.1727e-01,  1.0794e+00,  1.1545e-04, -1.3057e-01,
                       -1.5150e-01, -1.8105e+00, -1.9922e+00, -9.4149e-01,  1.7160e+00,
                        7.2539e-01, -1.5859e+00,  1.1179e+00,  2.4724e-01,  2.2715e-02,
                       -5.5386e-01, -6.4163e-02,  1.3208e+00, -1.7324e+00,  8.2149e-01,
                       -1.6027e-01, -6.0820e-01, -5.3839e-02,  8.7753e-01, -1.8351e+00,
                        9.4154e-01,  1.1150e-06, -1.1010e+00,  1.8903e-07, -7.8785e-02,
                        1.5185e-02, -3.4920e-01,  5.7173e-01, -5.2067e-01, -5.5273e-01,
                        2.3319e+00, -9.1125e-01, -5.5972e-01, -5.0869e-07,  2.9842e-01,
                        3.6933e-02,  9.8900e-01,  6.3460e-01, -3.3133e-01,  1.2709e+00,
                        3.8356e-01,  2.7952e-01, -8.9382e-01,  1.3201e+00,  3.1108e-02,
                        8.9526e-01, -2.5980e+00,  1.4346e+00,  2.2655e-01], device='cuda:0')),
              ('bn1.running_var',
               tensor([2.7965e+00, 5.0442e+00, 2.6717e-11, 1.6529e+00, 9.9016e-14, 1.0902e+00,
                       1.4707e+01, 2.8475e-12, 1.7844e+00, 1.0161e-09, 6.2115e+00, 2.5129e+00,
                       1.8872e+00, 2.2165e-08, 9.3744e+00, 8.5575e-01, 4.2712e+00, 2.1540e+00,
                       1.8649e+00, 8.2569e+00, 3.4079e+00, 3.7847e+00, 4.3678e+00, 5.9749e-01,
                       1.0354e+00, 6.1368e+00, 1.8832e+01, 8.7063e+00, 1.1364e+01, 1.3251e+00,
                       3.3312e+00, 1.4707e+00, 2.8365e+00, 1.2762e+01, 2.1264e+00, 2.8477e+00,
                       6.1466e-13, 1.1285e+00, 6.7986e-14, 5.4397e-01, 3.3953e-01, 1.9462e+00,
                       3.4749e+00, 2.1053e+00, 2.9347e+00, 4.5882e+00, 1.3855e+00, 1.3789e+00,
                       1.3027e-13, 1.5768e+00, 6.6004e-01, 2.2308e+00, 1.1185e+01, 8.2802e-01,
                       1.5758e+00, 1.0013e+00, 2.5887e+00, 7.7641e+00, 3.1521e+00, 1.6314e+00,

In [4]:
load_model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")


img = cv2.imread('/home/polymorvic/development/deep-peep-snooker/skip_test.png').astype(np.float32)
img = prepare_img_for_resnet(img)
img = img.unsqueeze(0)

with torch.no_grad():
    y_hat = load_model(img)
    probs = F.sigmoid(y_hat)

NameError: name 'prepare_img_for_resnet' is not defined

In [6]:
probs

tensor([[0.5538]])

In [29]:
with open("split_spec.json", encoding="utf-8") as f:
    split_spec = json.load(f)

In [30]:
import random

In [31]:
val_pics = []
for _ in range(16):

    while True:
        pic = random.choice(split_spec['val'])
        if pic not in val_pics:
            val_pics.append(pic)
            break

In [32]:
df = pd.read_csv('shot_labels.csv')

In [33]:
val_pics

['05_0016',
 'skip_m08_0034',
 'skip_m10_0019',
 '05_0011',
 '06_0038',
 'skip_m09_0012',
 'skip_m10_0005',
 '04_0023',
 'skip_m09_0058',
 'skip_m10_0010',
 'skip_m10_0021',
 'skip_m08_0014',
 '05_0043',
 'skip_m10_0045',
 '05_0057',
 'skip_m10_0027']

In [34]:
val_df = df[df['img_name'].isin(val_pics)]

In [14]:
val_df

           img_name  label     match
369         06_0020      1       m06
412         05_0027      1       m05
461   skip_m09_0009      0  skip_m09
620   skip_m09_0008      0  skip_m09
644         06_0003      1       m06
670   skip_m09_0011      0  skip_m09
718         04_0049      1       m04
982   skip_m10_0021      0  skip_m10
1033  skip_m10_0016      0  skip_m10
1040  skip_m09_0023      0  skip_m09
1113  skip_m09_0042      0  skip_m09
1224  skip_m09_0005      0  skip_m09
1290  skip_m10_0012      0  skip_m10
1390        04_0005      1       m04
1732  skip_m10_0007      0  skip_m10
1753        04_0046      1       m04

In [35]:
# load_model = models.resnet18()


# load_model.fc = nn.Sequential(
#     nn.Linear(load_model.fc.in_features, 256),
#     nn.ReLU(),
#     nn.Dropout(0.4),
#     nn.Linear(256, 64),
#     nn.ReLU(),
#     nn.Dropout(0.3),
#     nn.Linear(64, 1),
# )


# load_model.state_dict(torch.load('/home/polymorvic/development/deep-peep-snooker/models/v5/shot-classifier-best.pt', weights_only=True))

# load_model.eval()
# device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")

In [ ]:
images = []
labels = []
preds = []
for _, row in val_df.iterrows():
    img_name = row['img_name']
    dir = 'pics/' if 'skip_' not in img_name else 'pics/skip/'
    image = cv2.imread(f'../{dir}{img_name}.png')
    images.append(image)

    labels.append(row['label'])


    image = prepare_img_for_resnet(image)
    image = image.unsqueeze(0)
    image = image.to(device)

    with torch.no_grad():
        y_hat = model(image)
        # print(y_hat)
        prob = F.sigmoid(y_hat)
        print(prob)

    preds.append(prob)

tensor([[0.0492]], device='cuda:0')
tensor([[0.7225]], device='cuda:0')
tensor([[0.0351]], device='cuda:0')
tensor([[0.0368]], device='cuda:0')
tensor([[0.0549]], device='cuda:0')
tensor([[0.8679]], device='cuda:0')
tensor([[0.0515]], device='cuda:0')
tensor([[0.7127]], device='cuda:0')
tensor([[0.0228]], device='cuda:0')
tensor([[0.0433]], device='cuda:0')
tensor([[0.8765]], device='cuda:0')
tensor([[0.0312]], device='cuda:0')
tensor([[0.8623]], device='cuda:0')
tensor([[0.8867]], device='cuda:0')
tensor([[0.0199]], device='cuda:0')
tensor([[0.0427]], device='cuda:0')

In [ ]:
val_df

           img_name  label     match
146   skip_m10_0005      0  skip_m10
188         05_0016      1       m05
265   skip_m10_0019      0  skip_m10
348   skip_m09_0012      0  skip_m09
404   skip_m10_0045      0  skip_m10
482         05_0043      1       m05
699   skip_m10_0027      0  skip_m10
740         06_0038      1       m06
749   skip_m08_0034      0  skip_m08
982   skip_m10_0021      0  skip_m10
992         05_0057      1       m05
1010  skip_m08_0014      0  skip_m08
1115        04_0023      1       m04
1219        05_0011      1       m05
1629  skip_m09_0058      0  skip_m09
1693  skip_m10_0010      0  skip_m10